# Face Recognition Project Configuration
project:
  name: "Face Recognition Evaluation"
  version: "1.0.0"
  author: "AI Developer Intern"

# Dataset Configuration
dataset:
  raw_path: "data/raw"
  processed_path: "data/processed"
  train_path: "data/train"
  eval_path: "data/evaluation"
  train_split: 0.7
  eval_split: 0.3
  min_images_per_identity: 2
  image_size: [224, 224]
  
# Data Preprocessing
preprocessing:
  face_detection_confidence: 0.9
  alignment_method: "mtcnn"
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  augmentation:
    horizontal_flip: 0.5
    rotation_range: 10
    brightness_range: 0.2
    contrast_range: 0.2

# Model Configuration
model:
  architecture: "arcface"  # Options: arcface, insightface, facenet, dlib
  backbone: "resnet50"
  embedding_size: 512
  pretrained: true
  dropout_rate: 0.1

# Training Configuration
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50
  optimizer: "adam"
  weight_decay: 1e-4
  scheduler: "cosine"
  early_stopping_patience: 10
  checkpoint_frequency: 5
  
# Loss Function
loss:
  type: "arcface"  # Options: arcface, triplet, center
  margin: 0.5
  scale: 64
  
# Evaluation Configuration
evaluation:
  similarity_metrics: ["cosine", "euclidean", "manhattan"]
  threshold_range: [0.1, 0.9]
  threshold_steps: 9
  far_values: [0.001, 0.01, 0.1]
  
# Visualization
visualization:
  plot_roc: true
  plot_precision_recall: true
  plot_similarity_distribution: true
  plot_confusion_matrix: true
  plot_training_curves: true
  
# Paths
paths:
  models: "models"
  results: "results"
  logs: "results/logs"
  plots: "results/plots"
  metrics: "results/metrics"
  report: "report"
  
# Hardware
hardware:
  device: "auto"  # auto, cpu, cuda
  num_workers: 4
  pin_memory: true